apiVersion: v1
kind: Service
metadata:
  name: ai-messenger-voicemail
spec:
  selector:
    app: ai-messenger-voicemail
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
